# SENSOR TYPES
RFXCOM_SENSOR_UNKNOWN   = 0
RFXCOM_SENSOR_X10       = 1
RFXCOM_SENSOR_SECURITY  = 2
RFXCOM_SENSOR_OREGON    = 3
RFXCOM_SENSOR_HOMEEASY  = 4
RFXCOM_SENSOR_KOPPLA    = 5
RFXCOM_SENSOR_RFXCOM    = 6